
SELECT * 
FROM EMPLOYEES
WHERE SALARY > 10000

/*UNION*/ /*UNION ALL*/ INTERSECT

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 100;

-- MINUS
SELECT * 
FROM EMPLOYEES
WHERE SALARY > 10000 AND DEPARTMENT_ID !=100;