



-- 2 BEST PROCIDURE JOIN TABEL 
SELECT EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
/* RIGHT LEFT CROSS */ INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;



-- 1 SELF JOIN TABLE
SELECT M.FIRST_NAME, E.FIRST_NAME 	 
FROM EMPLOYEES AS E
	JOIN  EMPLOYEES AS M          	
	ON E.EMPLOYEE_ID  = M.MANAGER_ID;

-- 2
SELECT DEPARTMENTS.DEPARTMENT_NAME
FROM DEPARTMENTS
	LEFT JOIN EMPLOYEES
		ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
WHERE EMPLOYEES.DEPARTMENT_ID IS NULL;


-- 3
SELECT  
	EMPLOYEES.FIRST_NAME,
    EMPLOYEES.SALARY,
    (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID) - EMPLOYEES.SALARY
FROM EMPLOYEES
	JOIN DEPARTMENTS
    ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;


-- 4     
SELECT DEPARTMENT_NAME, /*AVG(SALARY)*/MIN(SALARY)
FROM EMPLOYEES
	JOIN DEPARTMENTS
		ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID

GROUP BY DEPARTMENT_NAME        
HAVING MIN(SALARY) > 5000;        